version: 2.1

jobs:
  build-and-run-for-node:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npm start
workflows:
  sample:
    jobs:
      - build-and-run-for-node